### ISSUE TITLE
PDF missing links

### ISSUE THREAD

**Issue by git42leech** [giltesa/Game-Boy-Color-USB-C-Charging-Kit-Pro#2]
The "Installation Guide V2.3.pdf" doesn't have the links, works fine with the regular "Installation Guide.pdf".

The battery link gives 404, might be a national/location issue.

**Comment by giltesa** [comment]
Thank you, I updated it!
Yes, the battery has restrictions by country. It may not work with yours. I didn't have any problems in my country. You can use the size number to find another seller.
